name: Update gist with WakaTime stats
on:
  schedule:
    - cron: "25 4 * * *"
jobs:
  update-gist:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - name: Update gist
        uses: matchai/waka-box@master
        env:
          GH_TOKEN: ${{ secrets.GH_TOKEN }}
          GIST_ID: b020d20ee7b9b3afa767f6e2d9611c63
          WAKATIME_API_KEY: ${{ secrets.WAKATIME_API_KEY }}
